
spring:
  datasource:
<<<<<<< HEAD:src/main/resources/application.yml
#    url: jdbc:mysql://petpdb.citsvvicombz.ap-northeast-2.rds.amazonaws.com:3306/petPdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: petP
#    password: password
    url: jdbc:mysql://localhost:3306/pet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rkdmseodud930
=======
    url: jdbc:mysql://petpdb.citsvvicombz.ap-northeast-2.rds.amazonaws.com:3306/petpdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: petP
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
>>>>>>> 53f10bb7c5bc4348ab93f2b3a6207cf15320ac58:src/main/resources/application-prod.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size : 100
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug