
spring:
  datasource:
#    url: jdbc:mysql://petpdb.citsvvicombz.ap-northeast-2.rds.amazonaws.com:3306/petPdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: petP
#    password: password
    url: jdbc:mysql://localhost:3306/pet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rkdmseodud930

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size : 100
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug